#!/usr/bin/env python3
"""
build_landscape.py -- assemble DATA_LANDSCAPE.md.

Inputs
  src/.cache/landscape_fragments.md   generated by src/harvest_metadata.py (tables, field lists, join checks)
  src/landscape_authored.md           hand-written header, non-REST Section 2 entries, Sections 3-5

Section 2 entries are placed in a fixed reading order (ORDER below), renumbered, and every
"§2.N" cross-reference in the hand-written text is remapped to the new numbers.

Usage
  python3 src/harvest_metadata.py --offline && python3 src/build_landscape.py
"""
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
FRAG = HERE / ".cache" / "landscape_fragments.md"
AUTH = HERE / "landscape_authored.md"
OUT = HERE.parent / "DATA_LANDSCAPE.md"
frag = FRAG.read_text()
auth = AUTH.read_text()


def between(text, start, end=None):
    i = text.index(start) + len(start)
    j = text.index(end, i) if end else len(text)
    return text[i:j].strip("\n")


table_block = between(frag, "## Section 1 table", "## Excluded as noise")
n_rows = re.search(r"\((\d+) rows\)", table_block).group(1)
table = table_block.split("\n", 1)[1].strip("\n")
noise = between(frag, "## Excluded as noise", "## Token-secured Enterprise folders")
secured = between(frag, "## Token-secured Enterprise folders", "## Join checks")
checks = between(frag, "## Join checks", "## Section 2 details")
details = between(frag, "## Section 2 details")

rows = [l for l in table.splitlines() if re.match(r"^\| \d+ \|", l)]
tiers = {t: sum(1 for l in rows if l.rstrip(" |").split("|")[-1].strip() == t) for t in ("High", "Medium", "Low", "None")}
n_noise = sum(int(m) for m in re.findall(r"\((\d+)\):\*\*", noise))
n_secured = secured.count("`")


def split_entries(text):
    parts = re.split(r"(?m)^(?=### 2\.)", text)
    return [p.strip("\n") for p in parts if p.startswith("### 2.")]


gen = split_entries(details)
gen_by_num = {}
for e in gen:
    num = re.match(r"### 2\.(\d+) ", e).group(1)
    gen_by_num[num] = e

header = between(auth, "<!--HEADER-->", "<!--S2_HIGH_MANUAL-->")
high_manual = split_entries(between(auth, "<!--S2_HIGH_MANUAL-->", "<!--S2_MEDIUM_MANUAL-->"))
med_manual = split_entries(between(auth, "<!--S2_MEDIUM_MANUAL-->", "<!--S3-->"))
s3 = between(auth, "<!--S3-->", "<!--JOINCHECKS-->")
s4 = between(auth, "<!--S4-->", "<!--S5-->")
s5 = between(auth, "<!--S5-->")


def title_of(e):
    return re.match(r"### 2\.\S+ (.*) — (High|Medium)$", e.splitlines()[0]).group(1)


gen_titles = {title_of(e): num for num, e in gen_by_num.items()}
man = {title_of(e): e for e in high_manual + med_manual}

ORDER = [
    ("gen", "GlendaleOne External Requests"),
    ("gen", "GlendaleOne External Requests (Enterprise layer)"),
    ("man", "Local extract `data/GlendaleOne_External_Requests.csv`"),
    ("gen", "Code Compliance Cases - GlendaleOne"),
    ("man", "Local extract `data/Code_Compliance_Cases_GlendaleOne.csv`"),
    ("gen", "GlendaleOne Escalations"),
    ("gen", "GlendaleOne Escalations (Enterprise layer)"),
    ("gen", "GlendaleOne Escalations (portal item → Enterprise)"),
    ("gen", "Glendale Council Districts (Hosted)"),
    ("gen", "Council Districts (Enterprise AdminAreas)"),
    ("gen", "Address Points By Council Districts"),
    ("gen", "Census 2020 block population points"),
    ("man", "Esri Business Analyst `ACS_Population_Summary_<DISTRICT>.xlsx` (×6)"),
    ("man", "Esri Business Analyst `Demographic_and_Income_Profile_<DISTRICT>.xlsx` (×6)"),
    ("gen", "100-block address points"),
    ("gen", "Address points joined to APN"),
    ("gen", "Parcels (city)"),
    ("gen", "Assessor parcel view"),
    ("gen", "Block groups with Esri demographics and HUD QCT fields"),
    ("gen", "COG_Child_Poverty_Analysis"),
    ("gen", "Glendale Code Compliance Sub Grid"),
    ("gen", "Police grid with council district (`CC_DIST`)"),
    ("gen", "Registered neighborhoods with HOA / management company"),
    ("gen", "Sanitation day routes, routes and inspection areas"),
    ("gen", "Police Calls for Service"),
    ("gen", "Water Distribution Service Requests (Survey123)"),
    ("man", "GlendaleOne Public and Council Report (Power BI)"),
    ("man", "Code Compliance Public Dashboard (Power BI)"),
]
used_gen = {t for k, t in ORDER if k == "gen"}
missing = set(gen_titles) - used_gen
assert not missing, f"generated entries not placed: {missing}"
assert all(t in man for k, t in ORDER if k == "man"), "manual entry title mismatch"

old_to_new, new_titles, entries = {}, {}, []
for n, (kind, title) in enumerate(ORDER, 1):
    if kind == "gen":
        old_to_new[gen_titles[title]] = str(n)
        body = gen_by_num[gen_titles[title]]
    else:
        body = man[title]
    new_titles[title] = n
    entries.append(re.sub(r"^### 2\.\S+ ", f"### 2.{n} ", body, count=1))

workbooks = f"§2.{new_titles['Esri Business Analyst `ACS_Population_Summary_<DISTRICT>.xlsx` (×6)']}–§2.{new_titles['Esri Business Analyst `Demographic_and_Income_Profile_<DISTRICT>.xlsx` (×6)']}"
powerbi = f"§2.{new_titles['GlendaleOne Public and Council Report (Power BI)']}–§2.{new_titles['Code Compliance Public Dashboard (Power BI)']}"


def remap(text):
    text = text.replace("Esri workbooks §2.X", "Esri workbooks @@WB@@")
    text = text.replace("Esri workbooks (§2.X)", "Esri workbooks (@@WB@@)")
    text = text.replace("Power BI reports (§2.X)", "Power BI reports (@@PBI@@)")
    assert "§2.X" not in text, "unmapped §2.X placeholder"
    text = re.sub(r"§2\.(\d+)", lambda m: f"§2.{old_to_new[m.group(1)]}", text)
    return text.replace("@@WB@@", workbooks).replace("@@PBI@@", powerbi)


doc = []
doc.append(remap(header))
doc.append(f"""## 1. Summary table

One row per dataset: {n_rows} rows (**{tiers['High']} High**, **{tiers['Medium']} Medium**, {tiers['Low']} Low, {tiers['None']} None). Rows are sorted by relevance, then theme, then name. {n_noise} further services are excluded as noise and listed after the table.

**How to read the columns:**
- **Dataset:** Enterprise rows show the service path in backticks.
  - "also AGOL item …" means a portal item registers a layer of that service.
  - "registers …, layer named …" means a portal item that only points at one Enterprise layer; the layer's real name is quoted because several differ from the item title.
  - "mirror" marks a second copy of a High dataset.
- **Host:** where the data is served. "(via AGOL item)" means the portal item is only a pointer.
- **Access method:** "public/anonymous" means no login was needed. "on Open Data portal" means `opendata.glendaleaz.com` lists the item. A bold error is the service's own reply.
- **Row count:** for multi-layer services, the layers counted.
- **Date range / vintage:** the named date field's minimum → maximum where one was measured. Otherwise the layer's last data edit or the item's modified date. "not published" means the service exposes neither.
- **Council District:**
  - **Y:** a district field is present (named).
  - **N:** no district field, or the field is empty.
  - **Derivable (spatial):** needs a point-in-polygon or overlay against the district layer.
  - **Derivable (address match):** has address text only.
  - **N/A:** the dataset is not geographic.

{table}

### Excluded as noise ({n_noise} services)

{noise}

### Token-secured Enterprise folders ({n_secured // 2})

These folders answered `499 Token Required`; their services could not be listed: {secured}""")

doc.append(f"""## 2. Per-dataset detail

{len(entries)} entries, High first, then Medium. Each copy (mirror) or local extract sits directly after its primary. Mirrors list only their differences from the primary.

**Field table conventions:**
- **Description:** quoted from the publisher's layer schema or item metadata where one exists; otherwise my reading, marked `[inferred]`.
- **Nulls / range / values:**
  - Populated share, counting nulls and empty strings separately.
  - Minimum → maximum for date fields.
  - Grouped value counts for categorical fields: the top 8, with the number of distinct values.
  - Notes on quirks.
  - Tags such as "[DATA_DICTIONARY.md, local extract]" mark notes carried from that file, not re-measured.
- **Cache files:** each table ends with a pointer to the cached statistics responses behind it.

""" + "\n\n".join(remap(e) for e in entries))

doc.append(remap(s3) + f"""

### Join checks

Counts come from `returnCountOnly` queries. Value comparisons use the full grouped value lists (`outStatistics`) of both fields. "Left" is the first field named. The raw results are in `src/.cache/join_checks.json`.

{checks}""")
doc.append(remap(s4))
doc.append(remap(s5))

text = "\n\n".join(d.strip("\n") for d in doc) + "\n"
OUT.write_text(text)
print(f"wrote {OUT}: {len(text.splitlines())} lines, {len(entries)} detail entries, map {old_to_new}")
